%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Christos\chris\auth\Timeseries\project\epilepticEEG.dat
%
% Auto-generated by MATLAB on 11-Jan-2022 19:57:56

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["e1", "Var2"];
opts.SelectedVariableNames = "e1";
opts.VariableTypes = ["double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "e1", "TrimNonNumeric", true);
opts = setvaropts(opts, "e1", "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Users\Christos\chris\auth\Timeseries\project\epilepticEEG.dat", opts);

%% Convert to output type
e1 = tbl.e1;

%% Clear temporary variables
clear opts tbl

% Plot the data
x = 1:3400;
y = e1;

f1 = figure("Name", "Timeserie", "NumberTitle", "off");
plot(x,y, "color", "#A2142F");